# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../design/gatheringWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_gatheringWindow(object):
    def setupUi(self, gatheringWindow):
        gatheringWindow.setObjectName("gatheringWindow")
        gatheringWindow.setWindowModality(QtCore.Qt.NonModal)
        # gatheringWindow.resize(1403, 847)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(gatheringWindow.sizePolicy().hasHeightForWidth())
        gatheringWindow.setSizePolicy(sizePolicy)
        # gatheringWindow.setMaximumSize(QtCore.QSize(1920, 9999))
        gatheringWindow.setStyleSheet("background-color: rgb(170, 170, 255);")
        gatheringWindow.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(gatheringWindow)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(-1, 2, 15, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(gatheringWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.barista_gigs_label = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.barista_gigs_label.sizePolicy().hasHeightForWidth())
        self.barista_gigs_label.setSizePolicy(sizePolicy)
        self.barista_gigs_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.barista_gigs_label.setStyleSheet("font: 15pt 'ubuntu';")
        self.barista_gigs_label.setObjectName("barista_gigs_label")
        self.horizontalLayout_6.addWidget(self.barista_gigs_label)
        spacerItem = QtWidgets.QSpacerItem(16777215, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.baristaLeft = QtWidgets.QPushButton(self.frame_2)
        self.baristaLeft.setMinimumSize(QtCore.QSize(269, 0))
        self.baristaLeft.setMaximumSize(QtCore.QSize(269, 16777215))
        self.baristaLeft.setObjectName("baristaLeft")
        self.horizontalLayout_6.addWidget(self.baristaLeft)
        self.baristaRight = QtWidgets.QPushButton(self.frame_2)
        self.baristaRight.setMinimumSize(QtCore.QSize(269, 0))
        self.baristaRight.setMaximumSize(QtCore.QSize(269, 16777215))
        self.baristaRight.setObjectName("baristaRight")
        self.horizontalLayout_6.addWidget(self.baristaRight)
        self.toggleCompletedGigs = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggleCompletedGigs.sizePolicy().hasHeightForWidth())
        self.toggleCompletedGigs.setSizePolicy(sizePolicy)
        self.toggleCompletedGigs.setMinimumSize(QtCore.QSize(269, 0))
        self.toggleCompletedGigs.setMaximumSize(QtCore.QSize(269, 30))
        self.toggleCompletedGigs.setObjectName("toggleCompletedGigs")
        self.horizontalLayout_6.addWidget(self.toggleCompletedGigs)
        self.verticalLayout.addWidget(self.frame_2)
        self.baristaFrame = QtWidgets.QFrame(gatheringWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baristaFrame.sizePolicy().hasHeightForWidth())
        self.baristaFrame.setSizePolicy(sizePolicy)
        self.baristaFrame.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.baristaFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.baristaFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.baristaFrame.setObjectName("baristaFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.baristaFrame)
        self.horizontalLayout.setContentsMargins(-1, 5, -1, 20)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.barista_1 = QtWidgets.QFrame(self.baristaFrame)
        self.barista_1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.barista_1.sizePolicy().hasHeightForWidth())
        self.barista_1.setSizePolicy(sizePolicy)
        self.barista_1.setMaximumSize(QtCore.QSize(350, 400))
        self.barista_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.barista_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.barista_1.setObjectName("barista_1")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.barista_1)
        self.verticalLayout_33.setContentsMargins(-1, 5, -1, 9)
        self.verticalLayout_33.setSpacing(2)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.barista_table_1 = QtWidgets.QLabel(self.barista_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.barista_table_1.sizePolicy().hasHeightForWidth())
        self.barista_table_1.setSizePolicy(sizePolicy)
        self.barista_table_1.setMinimumSize(QtCore.QSize(0, 20))
        self.barista_table_1.setMaximumSize(QtCore.QSize(400, 40))
        self.barista_table_1.setStyleSheet("font: 14pt 'ubuntu';\n"
"color: rgb(1, 42, 255);")
        self.barista_table_1.setWordWrap(True)
        self.barista_table_1.setObjectName("barista_table_1")
        self.verticalLayout_33.addWidget(self.barista_table_1)
        self.barista_date_1 = QtWidgets.QLabel(self.barista_1)
        self.barista_date_1.setObjectName("barista_date_1")
        self.barista_date_1.setStyleSheet("font: 12pt 'ubuntu';")
        self.verticalLayout_33.addWidget(self.barista_date_1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.barista_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 203, 306))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.barista_gig_1 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.barista_gig_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.barista_gig_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.barista_gig_1.setObjectName("barista_gig_1")
        self.barista_gig_layout_1 = QtWidgets.QVBoxLayout(self.barista_gig_1)
        self.barista_gig_layout_1.setContentsMargins(12, 12, 12, 12)
        self.barista_gig_layout_1.setSpacing(6)
        self.barista_gig_layout_1.setObjectName("barista_gig_layout_1")
        self.verticalLayout_17.addWidget(self.barista_gig_1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_33.addWidget(self.scrollArea_2)
        self.horizontalLayout.addWidget(self.barista_1)
        self.barista_2 = QtWidgets.QFrame(self.baristaFrame)
        self.barista_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.barista_2.sizePolicy().hasHeightForWidth())
        self.barista_2.setSizePolicy(sizePolicy)
        self.barista_2.setMaximumSize(QtCore.QSize(350, 400))
        self.barista_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.barista_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.barista_2.setObjectName("barista_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.barista_2)
        self.verticalLayout_11.setContentsMargins(-1, 5, -1, 9)
        self.verticalLayout_11.setSpacing(2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.barista_table_2 = QtWidgets.QLabel(self.barista_2)
        self.barista_table_2.setMinimumSize(QtCore.QSize(0, 20))
        self.barista_table_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.barista_table_2.setStyleSheet("font: 14pt 'ubuntu';\n"
"color: rgb(1, 42, 255);")
        self.barista_table_2.setWordWrap(True)
        self.barista_table_2.setObjectName("barista_table_2")
        self.verticalLayout_11.addWidget(self.barista_table_2)
        self.barista_date_2 = QtWidgets.QLabel(self.barista_2)
        self.barista_date_2.setObjectName("barista_date_2")
        self.barista_date_2.setStyleSheet("font: 12pt 'ubuntu';")
        self.verticalLayout_11.addWidget(self.barista_date_2)
        self.scrollArea = QtWidgets.QScrollArea(self.barista_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 202, 306))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.barista_gig_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.barista_gig_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.barista_gig_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.barista_gig_2.setObjectName("barista_gig_2")
        self.barista_gig_layout_2 = QtWidgets.QVBoxLayout(self.barista_gig_2)
        self.barista_gig_layout_2.setContentsMargins(12, 12, 12, 12)
        self.barista_gig_layout_2.setSpacing(6)
        self.barista_gig_layout_2.setObjectName("barista_gig_layout_2")
        self.verticalLayout_16.addWidget(self.barista_gig_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_11.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.barista_2)
        self.barista_3 = QtWidgets.QFrame(self.baristaFrame)
        self.barista_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.barista_3.sizePolicy().hasHeightForWidth())
        self.barista_3.setSizePolicy(sizePolicy)
        self.barista_3.setMaximumSize(QtCore.QSize(350, 400))
        self.barista_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.barista_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.barista_3.setObjectName("barista_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.barista_3)
        self.verticalLayout_12.setContentsMargins(-1, 5, -1, 9)
        self.verticalLayout_12.setSpacing(2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.barista_table_3 = QtWidgets.QLabel(self.barista_3)
        self.barista_table_3.setMinimumSize(QtCore.QSize(0, 20))
        self.barista_table_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.barista_table_3.setStyleSheet("font: 14pt 'ubuntu';\n"
"color: rgb(1, 42, 255);")
        self.barista_table_3.setWordWrap(True)
        self.barista_table_3.setObjectName("barista_table_3")
        self.verticalLayout_12.addWidget(self.barista_table_3)
        self.barista_date_3 = QtWidgets.QLabel(self.barista_3)
        self.barista_date_3.setObjectName("barista_date_3")
        self.barista_date_3.setStyleSheet("font: 12pt 'ubuntu';")
        self.verticalLayout_12.addWidget(self.barista_date_3)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.barista_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_3.sizePolicy().hasHeightForWidth())
        self.scrollArea_3.setSizePolicy(sizePolicy)
        self.scrollArea_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 203, 306))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_3.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_3.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.barista_gig_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.barista_gig_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.barista_gig_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.barista_gig_3.setObjectName("barista_gig_3")
        self.barista_gig_layout_3 = QtWidgets.QVBoxLayout(self.barista_gig_3)
        self.barista_gig_layout_3.setContentsMargins(12, 12, 12, 12)
        self.barista_gig_layout_3.setSpacing(6)
        self.barista_gig_layout_3.setObjectName("barista_gig_layout_3")
        self.verticalLayout_18.addWidget(self.barista_gig_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem3)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_12.addWidget(self.scrollArea_3)
        self.horizontalLayout.addWidget(self.barista_3)
        self.barista_4 = QtWidgets.QFrame(self.baristaFrame)
        self.barista_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.barista_4.sizePolicy().hasHeightForWidth())
        self.barista_4.setSizePolicy(sizePolicy)
        self.barista_4.setMaximumSize(QtCore.QSize(350, 400))
        self.barista_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.barista_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.barista_4.setObjectName("barista_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.barista_4)
        self.verticalLayout_13.setContentsMargins(-1, 5, -1, 9)
        self.verticalLayout_13.setSpacing(2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.barista_table_4 = QtWidgets.QLabel(self.barista_4)
        self.barista_table_4.setMinimumSize(QtCore.QSize(0, 20))
        self.barista_table_4.setMaximumSize(QtCore.QSize(16777215, 40))
        self.barista_table_4.setStyleSheet("font: 14pt 'ubuntu';\n"
"color: rgb(1, 42, 255);")
        self.barista_table_4.setWordWrap(True)
        self.barista_table_4.setObjectName("barista_table_4")
        self.verticalLayout_13.addWidget(self.barista_table_4)
        self.barista_date_4 = QtWidgets.QLabel(self.barista_4)
        self.barista_date_4.setObjectName("barista_date_4")
        self.barista_date_4.setStyleSheet("font: 12pt 'ubuntu';")
        self.verticalLayout_13.addWidget(self.barista_date_4)
        self.scrollArea_4 = QtWidgets.QScrollArea(self.barista_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_4.sizePolicy().hasHeightForWidth())
        self.scrollArea_4.setSizePolicy(sizePolicy)
        self.scrollArea_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 203, 306))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_4.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_4.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.barista_gig_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.barista_gig_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.barista_gig_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.barista_gig_4.setObjectName("barista_gig_4")
        self.barista_gig_layout_4 = QtWidgets.QVBoxLayout(self.barista_gig_4)
        self.barista_gig_layout_4.setContentsMargins(12, 12, 12, 12)
        self.barista_gig_layout_4.setSpacing(6)
        self.barista_gig_layout_4.setObjectName("barista_gig_layout_4")
        self.verticalLayout_19.addWidget(self.barista_gig_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem4)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_13.addWidget(self.scrollArea_4)
        self.horizontalLayout.addWidget(self.barista_4)
        self.barista_5 = QtWidgets.QFrame(self.baristaFrame)
        self.barista_5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.barista_5.sizePolicy().hasHeightForWidth())
        self.barista_5.setSizePolicy(sizePolicy)
        self.barista_5.setMaximumSize(QtCore.QSize(350, 400))
        self.barista_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.barista_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.barista_5.setObjectName("barista_5")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.barista_5)
        self.verticalLayout_14.setContentsMargins(-1, 5, -1, 9)
        self.verticalLayout_14.setSpacing(2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.barista_table_5 = QtWidgets.QLabel(self.barista_5)
        self.barista_table_5.setMinimumSize(QtCore.QSize(0, 20))
        self.barista_table_5.setMaximumSize(QtCore.QSize(16777215, 40))
        self.barista_table_5.setStyleSheet("font: 14pt 'ubuntu';\n"
"color: rgb(1, 42, 255);")
        self.barista_table_5.setWordWrap(True)
        self.barista_table_5.setObjectName("barista_table_5")
        self.verticalLayout_14.addWidget(self.barista_table_5)
        self.barista_date_5 = QtWidgets.QLabel(self.barista_5)
        self.barista_date_5.setObjectName("barista_date_5")
        self.barista_date_5.setStyleSheet("font: 12pt 'ubuntu';")
        self.verticalLayout_14.addWidget(self.barista_date_5)
        self.scrollArea_5 = QtWidgets.QScrollArea(self.barista_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_5.sizePolicy().hasHeightForWidth())
        self.scrollArea_5.setSizePolicy(sizePolicy)
        self.scrollArea_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 202, 306))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.barista_gig_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.barista_gig_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.barista_gig_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.barista_gig_5.setObjectName("barista_gig_5")
        self.barista_gig_layout_5 = QtWidgets.QVBoxLayout(self.barista_gig_5)
        self.barista_gig_layout_5.setContentsMargins(12, 12, 12, 12)
        self.barista_gig_layout_5.setSpacing(6)
        self.barista_gig_layout_5.setObjectName("barista_gig_layout_5")
        self.verticalLayout_20.addWidget(self.barista_gig_5)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem5)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_14.addWidget(self.scrollArea_5)
        self.horizontalLayout.addWidget(self.barista_5)
        self.barista_6 = QtWidgets.QFrame(self.baristaFrame)
        self.barista_6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.barista_6.sizePolicy().hasHeightForWidth())
        self.barista_6.setSizePolicy(sizePolicy)
        self.barista_6.setMaximumSize(QtCore.QSize(350, 400))
        self.barista_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.barista_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.barista_6.setObjectName("barista_6")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.barista_6)
        self.verticalLayout_15.setContentsMargins(-1, 5, -1, 9)
        self.verticalLayout_15.setSpacing(2)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.barista_table_6 = QtWidgets.QLabel(self.barista_6)
        self.barista_table_6.setMinimumSize(QtCore.QSize(0, 20))
        self.barista_table_6.setMaximumSize(QtCore.QSize(16777215, 40))
        self.barista_table_6.setStyleSheet("font: 14pt 'ubuntu';\n"
"color: rgb(1, 42, 255);")
        self.barista_table_6.setWordWrap(True)
        self.barista_table_6.setObjectName("barista_table_6")
        self.verticalLayout_15.addWidget(self.barista_table_6)
        self.barista_date_6 = QtWidgets.QLabel(self.barista_6)
        self.barista_date_6.setObjectName("barista_date_6")
        self.barista_date_6.setStyleSheet("font: 12pt 'ubuntu';")
        self.verticalLayout_15.addWidget(self.barista_date_6)
        self.scrollArea_6 = QtWidgets.QScrollArea(self.barista_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_6.sizePolicy().hasHeightForWidth())
        self.scrollArea_6.setSizePolicy(sizePolicy)
        self.scrollArea_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 203, 306))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_6.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_6.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_6)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.barista_gig_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents_6)
        self.barista_gig_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.barista_gig_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.barista_gig_6.setObjectName("barista_gig_6")
        self.barista_gig_layout_6 = QtWidgets.QVBoxLayout(self.barista_gig_6)
        self.barista_gig_layout_6.setContentsMargins(12, 12, 12, 12)
        self.barista_gig_layout_6.setSpacing(6)
        self.barista_gig_layout_6.setObjectName("barista_gig_layout_6")
        self.verticalLayout_21.addWidget(self.barista_gig_6)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem6)
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_6)
        self.verticalLayout_15.addWidget(self.scrollArea_6)
        self.horizontalLayout.addWidget(self.barista_6)
        self.verticalLayout.addWidget(self.baristaFrame)
        self.frame = QtWidgets.QFrame(gatheringWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chills_gigs_label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chills_gigs_label.sizePolicy().hasHeightForWidth())
        self.chills_gigs_label.setSizePolicy(sizePolicy)
        self.chills_gigs_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.chills_gigs_label.setStyleSheet("font: 15pt 'ubuntu';")
        self.chills_gigs_label.setObjectName("chills_gigs_label")
        self.horizontalLayout_2.addWidget(self.chills_gigs_label)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.chillsLeft = QtWidgets.QPushButton(self.frame)
        self.chillsLeft.setMinimumSize(QtCore.QSize(269, 0))
        self.chillsLeft.setMaximumSize(QtCore.QSize(269, 16777215))
        self.chillsLeft.setObjectName("chillsLeft")
        self.horizontalLayout_2.addWidget(self.chillsLeft)
        self.chillsRight = QtWidgets.QPushButton(self.frame)
        self.chillsRight.setMinimumSize(QtCore.QSize(269, 0))
        self.chillsRight.setMaximumSize(QtCore.QSize(269, 16777215))
        self.chillsRight.setObjectName("chillsRight")
        self.horizontalLayout_2.addWidget(self.chillsRight)
        self.verticalLayout.addWidget(self.frame)
        self.chillerFrame = QtWidgets.QFrame(gatheringWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chillerFrame.sizePolicy().hasHeightForWidth())
        self.chillerFrame.setSizePolicy(sizePolicy)
        self.chillerFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.chillerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chillerFrame.setObjectName("chillerFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.chillerFrame)
        self.horizontalLayout_4.setContentsMargins(-1, 5, -1, 20)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.chills_1 = QtWidgets.QFrame(self.chillerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chills_1.sizePolicy().hasHeightForWidth())
        self.chills_1.setSizePolicy(sizePolicy)
        self.chills_1.setMaximumSize(QtCore.QSize(300, 400))
        self.chills_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chills_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chills_1.setObjectName("chills_1")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.chills_1)
        self.verticalLayout_23.setContentsMargins(-1, 5, -1, 9)
        self.verticalLayout_23.setSpacing(2)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.chills_table_1 = QtWidgets.QLabel(self.chills_1)
        self.chills_table_1.setMinimumSize(QtCore.QSize(0, 20))
        self.chills_table_1.setMaximumSize(QtCore.QSize(16777215, 40))
        self.chills_table_1.setStyleSheet("font: 14pt 'ubuntu';\n"
"color: rgb(1, 42, 255);")
        self.chills_table_1.setWordWrap(True)
        self.chills_table_1.setObjectName("chills_table_1")
        self.verticalLayout_23.addWidget(self.chills_table_1)
        self.chills_date_1 = QtWidgets.QLabel(self.chills_1)
        self.chills_date_1.setObjectName("chills_date_1")
        self.chills_date_1.setStyleSheet("font: 12pt 'ubuntu';")
        self.verticalLayout_23.addWidget(self.chills_date_1)
        self.scrollArea_7 = QtWidgets.QScrollArea(self.chills_1)
        self.scrollArea_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_7.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollArea_7.setObjectName("scrollArea_7")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 203, 306))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_7.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_7.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.chills_gig_1 = QtWidgets.QFrame(self.scrollAreaWidgetContents_7)
        self.chills_gig_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.chills_gig_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chills_gig_1.setObjectName("chills_gig_1")
        self.chills_gig_layout_1 = QtWidgets.QVBoxLayout(self.chills_gig_1)
        self.chills_gig_layout_1.setObjectName("chills_gig_layout_1")
        self.verticalLayout_6.addWidget(self.chills_gig_1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_7)
        self.verticalLayout_23.addWidget(self.scrollArea_7)
        self.horizontalLayout_4.addWidget(self.chills_1)
        self.chills_2 = QtWidgets.QFrame(self.chillerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chills_2.sizePolicy().hasHeightForWidth())
        self.chills_2.setSizePolicy(sizePolicy)
        self.chills_2.setMaximumSize(QtCore.QSize(300, 400))
        self.chills_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chills_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chills_2.setObjectName("chills_2")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.chills_2)
        self.verticalLayout_24.setContentsMargins(-1, 5, -1, 9)
        self.verticalLayout_24.setSpacing(2)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.chills_table_2 = QtWidgets.QLabel(self.chills_2)
        self.chills_table_2.setMinimumSize(QtCore.QSize(0, 20))
        self.chills_table_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.chills_table_2.setStyleSheet("font: 14pt 'ubuntu';\n"
"color: rgb(1, 42, 255);")
        self.chills_table_2.setWordWrap(True)
        self.chills_table_2.setObjectName("chills_table_2")
        self.verticalLayout_24.addWidget(self.chills_table_2)
        self.chills_date_2 = QtWidgets.QLabel(self.chills_2)
        self.chills_date_2.setObjectName("chills_date_2")
        self.chills_date_2.setStyleSheet("font: 12pt 'ubuntu';")
        self.verticalLayout_24.addWidget(self.chills_date_2)
        self.scrollArea_8 = QtWidgets.QScrollArea(self.chills_2)
        self.scrollArea_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_8.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_8.setWidgetResizable(True)
        self.scrollArea_8.setObjectName("scrollArea_8")
        self.scrollAreaWidgetContents_8 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 202, 306))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_8.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_8.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_8.setObjectName("scrollAreaWidgetContents_8")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_8)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.chills_gig_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_8)
        self.chills_gig_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.chills_gig_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chills_gig_2.setObjectName("chills_gig_2")
        self.chills_gig_layout_2 = QtWidgets.QVBoxLayout(self.chills_gig_2)
        self.chills_gig_layout_2.setObjectName("chills_gig_layout_2")
        self.verticalLayout_22.addWidget(self.chills_gig_2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_22.addItem(spacerItem9)
        self.scrollArea_8.setWidget(self.scrollAreaWidgetContents_8)
        self.verticalLayout_24.addWidget(self.scrollArea_8)
        self.horizontalLayout_4.addWidget(self.chills_2)
        self.chills_3 = QtWidgets.QFrame(self.chillerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chills_3.sizePolicy().hasHeightForWidth())
        self.chills_3.setSizePolicy(sizePolicy)
        self.chills_3.setMaximumSize(QtCore.QSize(300, 400))
        self.chills_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chills_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chills_3.setObjectName("chills_3")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.chills_3)
        self.verticalLayout_25.setContentsMargins(-1, 5, -1, 9)
        self.verticalLayout_25.setSpacing(2)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.chills_table_3 = QtWidgets.QLabel(self.chills_3)
        self.chills_table_3.setMinimumSize(QtCore.QSize(0, 20))
        self.chills_table_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.chills_table_3.setStyleSheet("font: 14pt 'ubuntu' ;\n"
"color: rgb(1, 42, 255);")
        self.chills_table_3.setWordWrap(True)
        self.chills_table_3.setObjectName("chills_table_3")
        self.verticalLayout_25.addWidget(self.chills_table_3)
        self.chills_date_3 = QtWidgets.QLabel(self.chills_3)
        self.chills_date_3.setObjectName("chills_date_3")
        self.chills_date_3.setStyleSheet("font: 12pt 'ubuntu';")
        self.verticalLayout_25.addWidget(self.chills_date_3)
        self.scrollArea_9 = QtWidgets.QScrollArea(self.chills_3)
        self.scrollArea_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_9.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_9.setWidgetResizable(True)
        self.scrollArea_9.setObjectName("scrollArea_9")
        self.scrollAreaWidgetContents_9 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_9.setGeometry(QtCore.QRect(0, 0, 203, 306))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_9.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_9.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_9.setObjectName("scrollAreaWidgetContents_9")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_9)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.chills_gig_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_9)
        self.chills_gig_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.chills_gig_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chills_gig_3.setObjectName("chills_gig_3")
        self.chills_gig_layout_3 = QtWidgets.QVBoxLayout(self.chills_gig_3)
        self.chills_gig_layout_3.setObjectName("chills_gig_layout_3")
        self.verticalLayout_26.addWidget(self.chills_gig_3)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_26.addItem(spacerItem10)
        self.scrollArea_9.setWidget(self.scrollAreaWidgetContents_9)
        self.verticalLayout_25.addWidget(self.scrollArea_9)
        self.horizontalLayout_4.addWidget(self.chills_3)
        self.chills_4 = QtWidgets.QFrame(self.chillerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chills_4.sizePolicy().hasHeightForWidth())
        self.chills_4.setSizePolicy(sizePolicy)
        self.chills_4.setMaximumSize(QtCore.QSize(300, 400))
        self.chills_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chills_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chills_4.setObjectName("chills_4")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.chills_4)
        self.verticalLayout_27.setContentsMargins(-1, 5, -1, 9)
        self.verticalLayout_27.setSpacing(2)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.chills_table_4 = QtWidgets.QLabel(self.chills_4)
        self.chills_table_4.setMinimumSize(QtCore.QSize(0, 20))
        self.chills_table_4.setMaximumSize(QtCore.QSize(16777215, 40))
        self.chills_table_4.setStyleSheet("font: 14pt 'ubuntu';\n"
"color: rgb(1, 42, 255);")
        self.chills_table_4.setWordWrap(True)
        self.chills_table_4.setObjectName("chills_table_4")
        self.verticalLayout_27.addWidget(self.chills_table_4)
        self.chills_date_4 = QtWidgets.QLabel(self.chills_4)
        self.chills_date_4.setObjectName("chills_date_4")
        self.chills_date_4.setStyleSheet("font: 12pt 'ubuntu';")
        self.verticalLayout_27.addWidget(self.chills_date_4)
        self.scrollArea_10 = QtWidgets.QScrollArea(self.chills_4)
        self.scrollArea_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_10.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_10.setWidgetResizable(True)
        self.scrollArea_10.setObjectName("scrollArea_10")
        self.scrollAreaWidgetContents_10 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_10.setGeometry(QtCore.QRect(0, 0, 203, 306))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_10.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_10.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_10.setObjectName("scrollAreaWidgetContents_10")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_10)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.chills_gig_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_10)
        self.chills_gig_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.chills_gig_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chills_gig_4.setObjectName("chills_gig_4")
        self.chills_gig_layout_4 = QtWidgets.QVBoxLayout(self.chills_gig_4)
        self.chills_gig_layout_4.setObjectName("chills_gig_layout_4")
        self.verticalLayout_28.addWidget(self.chills_gig_4)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_28.addItem(spacerItem11)
        self.scrollArea_10.setWidget(self.scrollAreaWidgetContents_10)
        self.verticalLayout_27.addWidget(self.scrollArea_10)
        self.horizontalLayout_4.addWidget(self.chills_4)
        self.chills_5 = QtWidgets.QFrame(self.chillerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chills_5.sizePolicy().hasHeightForWidth())
        self.chills_5.setSizePolicy(sizePolicy)
        self.chills_5.setMaximumSize(QtCore.QSize(300, 400))
        self.chills_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chills_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chills_5.setObjectName("chills_5")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.chills_5)
        self.verticalLayout_29.setContentsMargins(-1, 5, -1, 9)
        self.verticalLayout_29.setSpacing(2)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.chills_table_5 = QtWidgets.QLabel(self.chills_5)
        self.chills_table_5.setMinimumSize(QtCore.QSize(0, 20))
        self.chills_table_5.setMaximumSize(QtCore.QSize(16777215, 40))
        self.chills_table_5.setStyleSheet("font: 14pt 'ubuntu';\n"
"color: rgb(1, 42, 255);")
        self.chills_table_5.setWordWrap(True)
        self.chills_table_5.setObjectName("chills_table_5")
        self.verticalLayout_29.addWidget(self.chills_table_5)
        self.chills_date_5 = QtWidgets.QLabel(self.chills_5)
        self.chills_date_5.setObjectName("chills_date_5")
        self.chills_date_5.setStyleSheet("font: 12pt 'ubuntu';")
        self.verticalLayout_29.addWidget(self.chills_date_5)
        self.scrollArea_11 = QtWidgets.QScrollArea(self.chills_5)
        self.scrollArea_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_11.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_11.setWidgetResizable(True)
        self.scrollArea_11.setObjectName("scrollArea_11")
        self.scrollAreaWidgetContents_11 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_11.setGeometry(QtCore.QRect(0, 0, 202, 306))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_11.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_11.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_11.setObjectName("scrollAreaWidgetContents_11")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_11)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.chills_gig_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_11)
        self.chills_gig_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.chills_gig_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chills_gig_5.setObjectName("chills_gig_5")
        self.chills_gig_layout_5 = QtWidgets.QVBoxLayout(self.chills_gig_5)
        self.chills_gig_layout_5.setObjectName("chills_gig_layout_5")
        self.verticalLayout_30.addWidget(self.chills_gig_5)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_30.addItem(spacerItem12)
        self.scrollArea_11.setWidget(self.scrollAreaWidgetContents_11)
        self.verticalLayout_29.addWidget(self.scrollArea_11)
        self.horizontalLayout_4.addWidget(self.chills_5)
        self.chills_6 = QtWidgets.QFrame(self.chillerFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chills_6.sizePolicy().hasHeightForWidth())
        self.chills_6.setSizePolicy(sizePolicy)
        self.chills_6.setMaximumSize(QtCore.QSize(300, 400))
        self.chills_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chills_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chills_6.setObjectName("chills_6")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.chills_6)
        self.verticalLayout_31.setSpacing(2)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.chills_table_6 = QtWidgets.QLabel(self.chills_6)
        self.chills_table_6.setMinimumSize(QtCore.QSize(0, 20))
        self.chills_table_6.setMaximumSize(QtCore.QSize(16777215, 40))
        self.chills_table_6.setStyleSheet("font: 14pt 'ubuntu';\n"
"color: rgb(1, 42, 255);")
        self.chills_table_6.setWordWrap(True)
        self.chills_table_6.setObjectName("chills_table_6")
        self.verticalLayout_31.addWidget(self.chills_table_6)
        self.chills_date_6 = QtWidgets.QLabel(self.chills_6)
        self.chills_date_6.setObjectName("chills_date_6")
        self.chills_date_6.setStyleSheet("font: 12pt 'ubuntu';")
        self.verticalLayout_31.addWidget(self.chills_date_6)
        self.scrollArea_12 = QtWidgets.QScrollArea(self.chills_6)
        self.scrollArea_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_12.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_12.setWidgetResizable(True)
        self.scrollArea_12.setObjectName("scrollArea_12")
        self.scrollAreaWidgetContents_12 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_12.setGeometry(QtCore.QRect(0, 0, 203, 302))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_12.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_12.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_12.setObjectName("scrollAreaWidgetContents_12")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_12)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.chills_gig_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents_12)
        self.chills_gig_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.chills_gig_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chills_gig_6.setObjectName("chills_gig_6")
        self.chills_gig_layout_6 = QtWidgets.QVBoxLayout(self.chills_gig_6)
        self.chills_gig_layout_6.setObjectName("chills_gig_layout_6")
        self.verticalLayout_32.addWidget(self.chills_gig_6)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_32.addItem(spacerItem13)
        self.scrollArea_12.setWidget(self.scrollAreaWidgetContents_12)
        self.verticalLayout_31.addWidget(self.scrollArea_12)
        self.horizontalLayout_4.addWidget(self.chills_6)
        self.verticalLayout.addWidget(self.chillerFrame)

        self.retranslateUi(gatheringWindow)
        QtCore.QMetaObject.connectSlotsByName(gatheringWindow)

    def retranslateUi(self, gatheringWindow):
        _translate = QtCore.QCoreApplication.translate
        gatheringWindow.setWindowTitle(_translate("gatheringWindow", "Te Huinga/The Gathering"))
        self.barista_gigs_label.setText(_translate("gatheringWindow", "Barista Gigs"))
        self.baristaLeft.setText(_translate("gatheringWindow", "Go Left"))
        self.baristaRight.setText(_translate("gatheringWindow", "Go Right"))
        self.toggleCompletedGigs.setText(_translate("gatheringWindow", "Show COMPLETED Gigs"))
        self.barista_table_1.setText(_translate("gatheringWindow", "Table: Table Name"))
        self.barista_date_1.setText(_translate("gatheringWindow", "Ordered at:"))
        self.barista_table_2.setText(_translate("gatheringWindow", "Table: Table Name"))
        self.barista_date_2.setText(_translate("gatheringWindow", "Ordered at:"))
        self.barista_table_3.setText(_translate("gatheringWindow", "Table: Table Name"))
        self.barista_date_3.setText(_translate("gatheringWindow", "Ordered at:"))
        self.barista_table_4.setText(_translate("gatheringWindow", "Table: Table Name"))
        self.barista_date_4.setText(_translate("gatheringWindow", "Ordered at:"))
        self.barista_table_5.setText(_translate("gatheringWindow", "Table: Table Name"))
        self.barista_date_5.setText(_translate("gatheringWindow", "Ordered at:"))
        self.barista_table_6.setText(_translate("gatheringWindow", "Table: Table Name"))
        self.barista_date_6.setText(_translate("gatheringWindow", "Ordered at:"))
        self.chills_gigs_label.setText(_translate("gatheringWindow", "Chills Gigs"))
        self.chillsLeft.setText(_translate("gatheringWindow", "Go Left"))
        self.chillsRight.setText(_translate("gatheringWindow", "Go Right"))
        self.chills_table_1.setText(_translate("gatheringWindow", "Table: Table Name"))
        self.chills_date_1.setText(_translate("gatheringWindow", "Ordered at:"))
        self.chills_table_2.setText(_translate("gatheringWindow", "Table: Table Name"))
        self.chills_date_2.setText(_translate("gatheringWindow", "Ordered at:"))
        self.chills_table_3.setText(_translate("gatheringWindow", "Table: Table Name"))
        self.chills_date_3.setText(_translate("gatheringWindow", "Ordered at:"))
        self.chills_table_4.setText(_translate("gatheringWindow", "Table: Table Name"))
        self.chills_date_4.setText(_translate("gatheringWindow", "Ordered at:"))
        self.chills_table_5.setText(_translate("gatheringWindow", "Table: Table Name"))
        self.chills_date_5.setText(_translate("gatheringWindow", "Ordered at:"))
        self.chills_table_6.setText(_translate("gatheringWindow", "Table: Table Name"))
        self.chills_date_6.setText(_translate("gatheringWindow", "Ordered at:"))

import workSpaceRes_rc
